FROM maven:3.5.2-jdk-8
USER root
RUN mkdir -p /home/automationFramework1
WORKDIR /home/automationFramework1/
RUN apt-get update
RUN yes | apt-get install iputils-ping
RUN yes | apt-get install git
ADD https://api.github.com/repos/sandraj-cuelogic/cyclopsAutomationDocker/git/refs/heads/master version.json
RUN git clone -b master https://github.com/sandraj-cuelogic/cyclopsAutomationDocker.git 
RUN echo "Build has been created successfully"
WORKDIR cyclopsAutomationDocker/
CMD mvn clean install
CMD mvn test
#RUN ping google.com